#!/bin/sh

XVFB=/usr/bin/Xvfb
XVFBARGS=":0 -nolisten tcp -fbdir /var/run -screen 0 1280x800x24+32"
PIDFILE=/var/run/xvfb.pid

case "$1" in
  start)
    start-stop-daemon --start --quiet --pidfile $PIDFILE --make-pidfile --background --exec $XVFB -- $XVFBARGS
    ;;
  stop)
    start-stop-daemon --stop --quiet --pidfile $PIDFILE
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/xvfb {start|stop|restart}"
    exit 1
esac

exit 0
